export const FETCH_API_START = "FETCH_API_START";
export const FETCH_API_SUCCESS = "FETCH_API_SUCCESS";
export const FETCH_API_FAIL = "FETCH_API_FAIL";

export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_ITEM_QTY = "ADJUST_ITEM_QTY";
export const SET_PRODUCTS = "SET_PRODUCTS";
